Set home page logo w/title and subtitle
BuidlGuidl/batch1.buidlguidl.com pull request #23
Opened 2024-01-18 23:07 UTC by GusMeg

## Description

Included a Dall-E made up image as our Batch 1 Logo.
Added the image to our homepage w/title and subtitle.

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #7 

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: gusmeg.eth

2024-01-19 15:31 UTC, carletex commented on packages/hardhat/contracts/Registerv2.sol
Let's remove this file from the PR!

2024-01-19 15:32 UTC, carletex requested changes
Left a tiny comment @GusMeg 

Homepage looking good :D

2024-01-19 16:23 UTC, JollyRogerz approved these changes
Awesome logo

2024-01-20 23:33 UTC, GusMeg commented on packages/hardhat/contracts/Registerv2.sol
Whoops... that shold've not been there. I just removed it from the branch.

2024-01-22 12:12 UTC, carletex approved these changes

2024-01-22 12:12 UTC, merged